source = $HOME/.config/hypr/style.conf

# BACKGROUND
background {
    monitor = 
    path = /home/rumi/Pictures/wallpapers/mocha-unix.png
    color = $base
    blur_passes = 3
    blur_size = 4
    noise = 0.02
    contrast = 0.9
    brightness = 0.8
    vibrancy = 0.2
    vibrancy_darkness = 0.0
}


# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# GREETINGS
label {
    monitor =
    text =Welcome!
    color = $text
    font_size = 55
    font_family = JetBrainsMono Nerd Font
    position = 165, 320
    halign = left
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = $text
    font_size = 40
    font_family = JetBrainsMono Nerd Font
    position = 255, 240
    halign = left
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] date +"%A, %B %d"
    color = $text
    font_size = 20
    text_align = left
    font_family = JetBrainsMono Nerd Font
    position = 180, 175
    halign = left
    valign = center
}

# Profie-Photo
image {
    monitor =
    border_size = 1
    border_color = $blue
    size = 160
    rounding = -1
    rotate = 0
    reload_time = -1
    reload_cmd = 
    position = 249, 25
    halign = left
    valign = center
}

# USER-BOX
shape {
    monitor =
    size = 320, 55
    color = $text
    rounding = -1
    border_size = 0
    border_color = $text
    rotate = 0
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)

    position = 170, -140
    halign = left
    valign = center
}

# USER
label {
    monitor =
    text =  $USER
    color = $surface0
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 281, -140
    halign = left
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = $text
    inner_color = $text
    font_color = $surface0
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font
    placeholder_text = <i><span foreground="##ffffff99"> Enter Pass</span></i>
    hide_input = false
    position = 170, -220
    halign = left
    valign = center
}


# Music widget
$music = ~/.config/hypr/scripts/music.sh

# Music blur div
shape {
    monitor =
    size = 350, 110
    color = $base
    rounding = 20
    rotate = 0
    position = -630, -350
    halign = center
    valign = center
    zindex = 1
}

# Music Album Art
image {
    monitor =
    path = /tmp/hyprlock_music/album_art.png
    size = 86
    border_size = 3
    border_color = rgba(255, 255, 255, 0.8)
    rounding = 5
    rotate = 0
    reload_time = 2
    reload_cmd = ~/.config/hypr/scripts/music.sh --art
    position = 167, -350
    halign = left
    valign = center
    zindex = 5
}

# PLAYER TITLE
label {
    monitor =
    text = cmd[update:2000] ~/.config/hypr/scripts/music.sh --title
    color = $text
    font_size = 14
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 270, -340
    halign = left
    valign = center
    zindex = 5
}

# PLAYER ARTIST
label {
    monitor =
    text = cmd[update:2000] ~/.config/hypr/scripts/music.sh --artist
    color = $subtext1
    font_size = 12
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 270, -360
    halign = left
    valign = center
    zindex = 5
}

# PLAYER SOURCE
label {
    monitor =
    text = cmd[update:2000] ~/.config/hypr/scripts/music.sh --source
    color = $subtext0
    font_size = 11
    font_family = JetBrains Mono Nerd Font Mono
    position = 270, -378
    halign = left
    valign = center
    zindex = 5
}