-- Generated by Noctalia

local primary = "rgb(8839ef)"
local surface = "rgb(eff1f5)"
local secondary = "rgb(fe640b)"
local error = "rgb(d20f39)"

hl.config({
	general = {
		col = {
			active_border = primary,
			inactive_border = surface,
		},
	},

	group = {
		col = {
			border_active = secondary,
			border_inactive = surface,
			border_locked_active = error,
			border_locked_inactive = surface,
		},

		groupbar = {
			col = {
				active = secondary,
				inactive = surface,
				locked_active = error,
				locked_inactive = surface,
			},
		},
	},
})
