#!/bin/sh
MODESTR="Dark"
#show a message
notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Switching To $MODESTR Mode"


#set the GTK theme
gsettings set org.gnome.desktop.interface gtk-theme "Catppuccin-Mocha-Standard-Lavender-Dark"
gsettings set org.gnome.desktop.interface icon-theme "Reversal-cyan-dark"
#change the background image and be cool about it ;)
killall swaybg
swaybg -m fill -i ~/Pictures/wallpapers/axo1.png
