#!/bin/sh
MODESTR="Light"
#show a message
notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Switching To $MODESTR Mode"


#set the GTK theme
gsettings set org.gnome.desktop.interface gtk-theme "Catppuccin-Latte-Standard-Lavender-Light"
gsettings set org.gnome.desktop.interface icon-theme "Reversal-red"
#change the background image and be cool about it ;)
killall swaybg
swaybg -m fill -i ~/Pictures/wallpapers/axo2.png