#!/bin/bash

dark_mode(){
    MODESTR="Dark"
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Switching To $MODESTR Mode"
    
    # #set the GTK theme
    gsettings set org.gnome.desktop.interface gtk-theme "catppuccin-mocha-lavender-standard+default"
    gsettings set org.gnome.desktop.interface icon-theme "Reversal-purple-dark"
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
    

    #set hyprland theme
    cat ~/.config/hypr/mocha.conf > ~/.config/hypr/style.conf


    #set the wallpaper
    swww img ~/Pictures/wallpapers/axo-dark.png --transition-duration 1
    
    #set the kitty theme
    kitty +kitten themes --reload-in=all Catppuccin-Mocha

    #set rofi theme
    cat ~/.config/rofi/dark.rasi > ~/.config/rofi/config.rasi


    #set Discord css theme
    cat ~/.config/Vencord/themes/Mocha.theme.css > ~/.config/Vencord/themes/Catppuccin.theme.css
    
    #set Zathura theme
    cat ~/.config/zathura/catppuccin-mocha > ~/.config/zathura/zathurarc
    
    #set the waybar theme
    
    killall waybar
    cat ~/.config/waybar/mocha-style.css > ~/.config/waybar/style.css
    waybar

}


light_mode(){
    MODESTR="Light"
    
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Switching To $MODESTR Mode"
    #set the GTK theme
    gsettings set org.gnome.desktop.interface gtk-theme "catppuccin-latte-lavender-standard+default"
    gsettings set org.gnome.desktop.interface icon-theme "Reversal-purple"
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
    

    #set hyprland theme
    cat ~/.config/hypr/latte.conf > ~/.config/hypr/style.conf


    #set the wallpaper
    swww img ~/Pictures/wallpapers/axo-light.png --transition-duration 1

    #set the kitty theme
    kitty +kitten themes --reload-in=all Catppuccin-Latte

    #set rofi theme
    cat ~/.config/rofi/light.rasi > ~/.config/rofi/config.rasi
    
    #set Discord css theme
    cat ~/.config/Vencord/themes/Latte.theme.css > ~/.config/Vencord/themes/Catppuccin.theme.css
     
    #set Zathura theme
    cat ~/.config/zathura/catppuccin-latte > ~/.config/zathura/zathurarc



    #set the waybar theme
    
    killall waybar
    cat ~/.config/waybar/latte-style.css > ~/.config/waybar/style.css
    waybar
}

if [ "$1" == "--dark" ]; then
    dark_mode
    elif [ "$1" == "--light" ]; then
    light_mode
fi