#!/usr/bin/env bash

export STATUS_FILE="$XDG_RUNTIME_DIR/touchpad.status"

DEVICE="asup1205:00-093a:2008-touchpad"

enable_touchpad() {
    printf "true" >"$STATUS_FILE"
    notify-send -a "Touchpad" -t 1000 -u normal "Enabling touchpad"
    hyprctl eval "hl.device({ name = \"$DEVICE\", enabled = true })"
}

disable_touchpad() {
    printf "false" >"$STATUS_FILE"
    notify-send -a "Touchpad" -t 1000 -u normal "Disabling touchpad"
    hyprctl eval "hl.device({ name = \"$DEVICE\", enabled = false })"
}

if [ "$1" = "enable" ]; then
    enable_touchpad
elif [ "$1" = "disable" ]; then
    disable_touchpad
else
    # Toggle mode (no argument)
    if ! [ -f "$STATUS_FILE" ]; then
        enable_touchpad
    else
        if [ "$(cat "$STATUS_FILE")" = "true" ]; then
            disable_touchpad
        elif [ "$(cat "$STATUS_FILE")" = "false" ]; then
            enable_touchpad
        fi
    fi
fi