color0 #51576d
color1 #e78284
color2 #a6d189
color3 #e5c890
color4 #8caaee
color5 #f4b8e4
color6 #81c8be
color7 #a5adce
color8 #626880
color9 #e67172
color10 #8ec772
color11 #d9ba73
color12 #7b9ef0
color13 #f2a4db
color14 #5abfb5
color15 #b5bfe2

cursor                #f2d5cf
cursor_text_color     #303446
background            #303446
foreground            #c6d0f5
selection_foreground  #c6d0f5
selection_background  #626880
active_border_color   #8839ef
inactive_border_color #ccd0da
url_color             #8839ef

active_tab_foreground   #eff1f5
active_tab_background   #8839ef
inactive_tab_foreground #6c6f85
inactive_tab_background #ccd0da
cursor_trail_color      #6c6f85
