#!/bin/bash

NOTIFY="notify-send -a Brightness -t 1000 -h string:x-canonical-private-synchronous:sys-notify"

# --- Get Percentage ---
get_backlight() {
    echo $(( $(brightnessctl g) * 100 / $(brightnessctl m) ))
}

# --- Notify Logic ---
notify_brightness() {
    percent=$(get_backlight)
    $NOTIFY -h string:x-dunst-stack-tag:brightness_notif -h int:value:"$percent" -u low "Brightness: ${percent}%"
}

# --- Execute Command ---
case "$1" in
    --inc) brightnessctl set 5%+ && notify_brightness ;;
    --dec) brightnessctl set 5%- && notify_brightness ;;
    --get) brightnessctl g ;;
    *) get_backlight ;;
esac