#!/bin/bash

dark_mode(){

    # #set the GTK theme
    gsettings set org.gnome.desktop.interface gtk-theme "catppuccin-mocha-lavender-standard+default"
    gsettings set org.gnome.desktop.interface icon-theme "Reversal-purple-dark"
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
    
    #set hyprland theme
    cat ~/.config/hypr/mocha.conf > ~/.config/hypr/style.conf
    
    #set the kitty theme
    kitty +kitten themes --reload-in=all Catppuccin-Mocha
    
    #set rofi theme
    cat ~/.config/rofi/dark.rasi > ~/.config/rofi/config.rasi
    
    #set Discord css theme
    cat ~/.config/Vencord/themes/Mocha.theme.css > ~/.config/Vencord/themes/Catppuccin.theme.css
    
    #set Zathura theme
    cat ~/.config/zathura/catppuccin-mocha > ~/.config/zathura/zathurarc
    
    #set dunst theme
    cat ~/.config/dunst/mocha-dunst > ~/.config/dunst/dunstrc
    killall dunst
    dunst
    
    #set the wallpaper
    swww img ~/Pictures/wallpapers/axo-dark.png --transition-duration=1 --transition-step=1 --transition-fps=60 --transition-type=wave
    
    #set the notification
    MODESTR="Dark"
    notify-send -t 1000 -h string:x-canonical-private-synchronous:sys-notify -u low "Switching To $MODESTR Mode"
    
    #set the waybar theme
    cat ~/.config/waybar/mocha-style.css > ~/.config/waybar/style.css
    killall waybar
    waybar
}


light_mode(){
    
    #set the GTK theme
    gsettings set org.gnome.desktop.interface gtk-theme "catppuccin-latte-lavender-standard+default"
    gsettings set org.gnome.desktop.interface icon-theme "Reversal-purple"
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
    
    #set hyprland theme
    cat ~/.config/hypr/latte.conf > ~/.config/hypr/style.conf
    
    #set the kitty theme
    kitty +kitten themes --reload-in=all Catppuccin-Latte
    
    #set rofi theme
    cat ~/.config/rofi/light.rasi > ~/.config/rofi/config.rasi
    
    #set Discord css theme
    cat ~/.config/Vencord/themes/Latte.theme.css > ~/.config/Vencord/themes/Catppuccin.theme.css
    
    #set Zathura theme
    cat ~/.config/zathura/catppuccin-latte > ~/.config/zathura/zathurarc
    
    #set dunst theme
    cat ~/.config/dunst/latte-dunst > ~/.config/dunst/dunstrc
    killall dunst
    dunst
    
    #set the wallpaper
    swww img ~/Pictures/wallpapers/axo-light.png --transition-duration=1 --transition-step=1 --transition-fps=60 --transition-type=wave
    
    #set the notification
    MODESTR="Light"
    notify-send -t 1000 -h string:x-canonical-private-synchronous:sys-notify -u low "Switching To $MODESTR Mode"
    
    #set the waybar theme
    cat ~/.config/waybar/latte-style.css > ~/.config/waybar/style.css
    killall waybar
    waybar
}

if [ "$1" == "--dark" ]; then
    dark_mode
    elif [ "$1" == "--light" ]; then
    light_mode
fi