#!/bin/bash

set_theme() {
    local mode="$1"
    
    # Define variables based on the selected mode
    if [ "$mode" == "dark" ]; then
        wall_img="mocha-unix.png"
        gtk_theme="catppuccin-mocha-lavender-standard+default"
        icon_theme="Reversal-purple-dark"
        color_scheme="prefer-dark"
        cursor_theme="Catppuccin-Mocha-Light"
        hypr_cursor="catppuccin-mocha-light-cursors"
        hypr_conf="mocha.conf"
        kitty_theme="Catppuccin-Mocha"
        rofi_conf="dark.rasi"
        vencord_theme="Mocha.theme.css"
        zathura_conf="catppuccin-mocha"
        dunst_conf="mocha-dunst"
        waybar_conf="mocha-style.css"
        nwg_dock_conf="mocha-style.css"
    else
        wall_img="latte-unix.png"
        gtk_theme="catppuccin-latte-lavender-standard+default"
        icon_theme="Reversal-purple"
        color_scheme="prefer-light"
        cursor_theme="Catppuccin-Latte-Dark"
        hypr_cursor="catppuccin-latte-dark-cursors"
        hypr_conf="latte.conf"
        kitty_theme="Catppuccin-Latte"
        rofi_conf="light.rasi"
        vencord_theme="Latte.theme.css"
        zathura_conf="catppuccin-latte"
        dunst_conf="latte-dunst"
        waybar_conf="latte-style.css"
        nwg_dock_conf="latte-style.css"
    fi

    # Set the wallpaper (Decreased duration to 0.2s and increased FPS to 144)
    awww img ~/Pictures/wallpapers/"$wall_img" --transition-duration=0.2 --transition-step=1 --transition-type=fade
    
    # Set the GTK theme
    gsettings set org.gnome.desktop.interface gtk-theme "$gtk_theme"
    gsettings set org.gnome.desktop.interface icon-theme "$icon_theme"
    gsettings set org.gnome.desktop.interface color-scheme "$color_scheme"
    gsettings set org.gnome.desktop.interface cursor-theme "$cursor_theme"
    gsettings set org.gnome.desktop.interface cursor-size 24
    
    # Set Hyprland cursor and theme
    hyprctl setcursor "$hypr_cursor" 24
    cp -f ~/.config/hypr/"$hypr_conf" ~/.config/hypr/style.conf
    
    # Set the kitty theme
    kitty +kitten themes --reload-in=all "$kitty_theme"
    
    # Set rofi theme
    cp -f ~/.config/rofi/"$rofi_conf" ~/.config/rofi/config.rasi
    
    # Set Discord css theme
    cp -f ~/.config/Vencord/themes/"$vencord_theme" ~/.config/Vencord/themes/Catppuccin.theme.css
    
    # Set Zathura theme
    cp -f ~/.config/zathura/"$zathura_conf" ~/.config/zathura/zathurarc
    
    # Set dunst theme and restart cleanly in the background
    cp -f ~/.config/dunst/"$dunst_conf" ~/.config/dunst/dunstrc
    killall -q dunst
    dunst & disown
    
    # Set the waybar theme and restart cleanly in the background
    cp -f ~/.config/waybar/"$waybar_conf" ~/.config/waybar/style.css
    killall -q waybar
    waybar > /dev/null 2>&1 & disown

    # Set the nwg-dock-hyprland theme and restart cleanly in the background
    cp -f ~/.config/nwg-dock-hyprland/"$nwg_dock_conf" ~/.config/nwg-dock-hyprland/style.css
    killall -q nwg-dock-hyprland
    sleep 0.2 # Brief pause to ensure the old instance releases the socket completely
    nwg-dock-hyprland -r -p bottom -a center -mb 15 -ml 15 -mr 15 -i 36 -c "rofi -show drun" > /dev/null 2>&1 & disown
}

# Execute based on arguments
if [ "$1" == "--dark" ]; then
    set_theme "dark"
elif [ "$1" == "--light" ]; then
    set_theme "light"
else
    echo "Usage: $0 [--dark|--light]"
    exit 1
fi