#!/bin/bash

dark_mode(){
    
    #set the wallpaper
    swww img ~/Pictures/wallpapers/axo-dark.png --transition-duration=1 --transition-step=1 --transition-fps=60 --transition-type=wave
    
    # #set the GTK theme
    gsettings set org.gnome.desktop.interface gtk-theme catppuccin-mocha-lavender-standard+default
    gsettings set org.gnome.desktop.interface icon-theme "Reversal-purple-dark"
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
    gsettings set org.gnome.desktop.interface cursor-theme Catppuccin-Mocha-Light
    gsettings set org.gnome.desktop.interface cursor-size 24
    hyprctl setcursor catppuccin-mocha-light-cursors 24
    #set hyprland theme
    cat ~/.config/hypr/mocha.conf > ~/.config/hypr/style.conf
    
    #set the kitty theme
    kitty +kitten themes --reload-in=all Catppuccin-Mocha
    
    #set rofi theme
    cat ~/.config/rofi/dark.rasi > ~/.config/rofi/config.rasi
    
    #set Discord css theme
    cat ~/.config/Vencord/themes/Mocha.theme.css > ~/.config/Vencord/themes/Catppuccin.theme.css
    
    #set Zathura theme
    cat ~/.config/zathura/catppuccin-mocha > ~/.config/zathura/zathurarc
    
    #set dunst theme
    cat ~/.config/dunst/mocha-dunst > ~/.config/dunst/dunstrc
    sleep 1
    killall dunst
    sleep 1
    dunst
    
    #set the waybar theme
    cat ~/.config/waybar/mocha-style.css > ~/.config/waybar/style.css
    sleep 1
    killall waybar
    sleep 1
    waybar
}


light_mode(){
    
    #set the wallpaper
    swww img ~/Pictures/wallpapers/axo-light.png --transition-duration=1 --transition-step=1 --transition-fps=60 --transition-type=wave
    
    #set the GTK theme
    gsettings set org.gnome.desktop.interface gtk-theme catppuccin-latte-lavender-standard+default
    gsettings set org.gnome.desktop.interface icon-theme "Reversal-purple"
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'

    gsettings set org.gnome.desktop.interface cursor-theme Catppuccin-Latte-Dark
    gsettings set org.gnome.desktop.interface cursor-size 24
    hyprctl setcursor catppuccin-latte-dark-cursors 24
    
    #set hyprland theme
    cat ~/.config/hypr/latte.conf > ~/.config/hypr/style.conf
    
    #set the kitty theme
    kitty +kitten themes --reload-in=all Catppuccin-Latte
    
    #set rofi theme
    cat ~/.config/rofi/light.rasi > ~/.config/rofi/config.rasi
    
    #set Discord css theme
    cat ~/.config/Vencord/themes/Latte.theme.css > ~/.config/Vencord/themes/Catppuccin.theme.css
    
    #set Zathura theme
    cat ~/.config/zathura/catppuccin-latte > ~/.config/zathura/zathurarc
    
    #set dunst theme
    cat ~/.config/dunst/latte-dunst > ~/.config/dunst/dunstrc
    sleep 1
    killall dunst
    sleep 1
    dunst
    
    #set the waybar theme
    cat ~/.config/waybar/latte-style.css > ~/.config/waybar/style.css
    sleep 1
    killall waybar
    sleep 1
    waybar
}

if [ "$1" == "--dark" ]; then
    dark_mode
    elif [ "$1" == "--light" ]; then
    light_mode
fi