#!/bin/bash

NOTIFY="notify-send -a Volume -t 1000 -h string:x-canonical-private-synchronous:sys-notify"

# --- Speaker Logic ---
notify_vol() {
    vol=$(pamixer --get-volume)
    mute=$(pamixer --get-mute)
    
    if [ "$mute" == "true" ] || [ "$vol" -eq 0 ]; then
        text="Volume Muted"
    else
        text="Volume: ${vol}%"
    fi

    $NOTIFY -h string:x-dunst-stack-tag:volume_notif -h int:value:"$vol" -u low "$text"
}

# --- Microphone Logic ---
notify_mic() {
    vol=$(pamixer --default-source --get-volume)
    mute=$(pamixer --default-source --get-mute)

    if [ "$mute" == "true" ] || [ "$vol" -eq 0 ]; then
        text="Microphone Muted"
    else
        text="Mic-Level: ${vol}%"
    fi

    $NOTIFY -h string:x-dunst-stack-tag:mic_notif -h int:value:"$vol" -u low "$text"
}

# --- Execute Command ---
case "$1" in
    --inc) pamixer -i 5 && notify_vol ;;
    --dec) pamixer -d 5 && notify_vol ;;
    --toggle) pamixer -t && notify_vol ;;
    --mic-inc) pamixer --default-source -i 5 && notify_mic ;;
    --mic-dec) pamixer --default-source -d 5 && notify_mic ;;
    --toggle-mic) pamixer --default-source -t && notify_mic ;;
    *) pamixer --get-volume ;;
esac